#!/usr/bin/env python3

import sys
import subprocess

def justrunit(arglist):
    print(subprocess.check_output(arglist).decode('utf-8'))

def init_branch(startpoint):
    global initBranch, branchName

    try:
        justrunit(['git', 'checkout', branchName])
    except CalledProcessError as e:
        # If the branch does not exist, we need to create it.
        justrunit(['git', 'checkout', '-b', branchName, startpoint])
        print("Creating branch " + branchName)
    else:
        # If the branch already existed, we want to cherry-pick the
        # 'startpoint' commit.
        cherry_pick_theirs(startpoint)

    initBranch = True

# Pull a commit into the git repository.
def cherry_pick_theirs(revision):
    try:
        justrunit(['git', 'rm', '-rf', '.'])
    except:
        pass
    justrunit(['git', 'checkout', revision, '--', '.'])
    justrunit(['git', 'commit', '-C', revision])
    tag = subprocess.check_output(['git', 'log', '-1', '--pretty=%s', 'HEAD']).decode('utf-8').rstrip()
    justrunit(['git', 'tag', tag])
    

initBranch = False
for line in open(sys.argv[1]).readlines():
    revisions = [r for r in subprocess.check_output(['git', 'rev-list', '--reverse', line.rstrip()]).decode('utf-8').split('\n') if r.rstrip()]
    for revision in revisions:
        if not initBranch:
            init_branch(revision)
        else:
            cherry_pick_theirs(revision)
