# Version: MPL 1.1 / GPLv3+ / LGPLv3+
#
# The contents of this file are subject to the Mozilla Public License Version
# 1.1 (the "License"); you may not use this file except in compliance with
# the License or as specified alternatively below. You may obtain a copy of
# the License at http://www.mozilla.org/MPL/
#
# Software distributed under the License is distributed on an "AS IS" basis,
# WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
# for the specific language governing rights and limitations under the
# License.
#
# Major Contributor(s):
# Copyright (C) 2012 Red Hat, Inc., David Tardon <dtardon@redhat.com>
#  (initial developer)
#
# All Rights Reserved.
#
# For minor contributions see the git repository.
#
# Alternatively, the contents of this file may be used under the terms of
# either the GNU General Public License Version 3 or later (the "GPLv3+"), or
# the GNU Lesser General Public License Version 3 or later (the "LGPLv3+"),
# in which case the provisions of the GPLv3+ or the LGPLv3+ are applicable
# instead of those above.

proc libo_gdb_init {binfile dir} {
    gdb_exit
    gdb_start
    gdb_reinitialize_dir $dir
    gdb_load $binfile

    # FIXME: gdb version!
    gdb_test_no_output "set python print-stack on"
    gdb_test_no_output "set print pretty on"
}

proc libo_load_printers {modules {regfunc "register_pretty_printers"}} {
    set commands [list]
    foreach module $modules {
        lappend commands "python import libreoffice.$module" "python libreoffice.$module.${regfunc}(gdb)"
    }

    foreach command $commands {
        if { [gdb_test_no_output "$command"] } {
            return 0
        }
    }

    return 1
}

proc libo_runto {break_func} {
    set ok [runto $break_func]
    if { $ok } {
        set ok [expr [gdb_test finish {.*}] ? 0 : 1]
    }
    return $ok
}

proc libo_pp_test {var result} {
    return [gdb_test "print $var" "= $result"]
}

# vim:set shiftwidth=4 tabstop=4 expandtab:
