#!/usr/bin/env python

import sys
import email
import smtplib

def adddevlisttocc(message):
        devlist = 'LibreOffice Developer List <libreoffice@lists.freedesktop.org>'
        if 'cc' in message:
		cc = message['cc']
                del message['cc']
                message['cc'] = '%s, %s' % (cc, devlist)
        else:
                message['cc'] = devlist

message = email.message_from_file(sys.stdin)
adddevlisttocc(message)

# we are watching for comments but not sending mails for those in hope to evade
# https://code.google.com/p/gerrit/issues/detail?id=1465
if not message['X-Gerrit-MessageType'] == 'comment':
	server = smtplib.SMTP('localhost')
	server.sendmail('gerrit@libreoffice.org', 'libreoffice@lists.freedesktop.org', str(message))
	server.quit()
