#!/usr/bin/env python
#
# This file is part of the LibreOffice project.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

import os
import os.path
import logging
import minilog

repodir = os.path.join(os.environ['HOME'], 'syncrepos')
sourceurl = 'git://anongit.freedesktop.org/libreoffice/'
desturl = 'ssh://logerrit/'
repos = ['binfilter', 'core', 'contrib/dev-tools']
branches = {}
branches['binfilter'] = [
    'master',
    'libreoffice-3-5',
        'libreoffice-3-5-0',
        'libreoffice-3-5-1',
        'libreoffice-3-5-2',
        'libreoffice-3-5-3',
        'libreoffice-3-5-4',
        'libreoffice-3-5-5',
    'libreoffice-3-6',
        'libreoffice-3-6-0',
    # feature
        'feature/cmclayout',
        'feature/submodules',
    # distro
        'distro/ubuntu-oneiric-3.4'
    ]
branches['core'] = [
    'master',
    'libreoffice-3-5',
        'libreoffice-3-5-0',
        'libreoffice-3-5-1',
        'libreoffice-3-5-2',
        'libreoffice-3-5-3',
        'libreoffice-3-5-4',
        'libreoffice-3-5-5',
    'libreoffice-3-6',
        'libreoffice-3-6-0',
    # feature
        'feature/accfixes2',
        'feature/base-preview',
        'feature/calc-empty-string-config',
        'feature/cmclayouttrans',
        'feature/coretext',
        'feature/external_gbuild',
        'feature/gbuild_dictionaries',
        'feature/gbuild_help',
        'feature/gbuild_mkdir',
        'feature/gbuild_ure',
        'feature/gsoc-calc-perf',
        'feature/gsoc-calc-perf2',
        'feature/gsoc-test-improvements',
        'feature/gsoc-test-improvements2',
        'feature/gsoc-test-improvements3',
        'feature/gstreamer-1.0',
        'feature/layout',
        'feature/mork',
        'feature/opengl-canvas',
        'feature/orcus-integration',
        'feature/remote',
        'feature/stub-writer',
        'feature/submodules',
        'feature/unitymenus',
    # distro
        'distro/ubuntu-oneiric-3.4',
        'distro/ubuntu-oneiric-3.4-all'
    ]
branches['contrib/dev-tools'] = ['master']

loglevel='INFO'
logfile=os.path.join(os.environ['HOME'], 'sync.log')

class RepoSyncer():
    def __init__(self, repo, logger, loghandler):
        self.repo = repo
        self.logger = logger
        self.localpath = os.path.join(repodir, self.repo + '.git')

    def make_extra(self, phase):
        return { 'repo' : self.repo, 'phase' : phase }

    def ensure_exists(self, remotebaseurl):
        if not os.path.exists(self.localpath):
            os.makedirs(self.localpath)
            minilog.logged_call( \
                ['git', 'clone', '--bare', '--mirror', remotebaseurl + self.repo, self.localpath], \
                self.logger, \
                self.make_extra('clone'))

    def update_repo(self):
        minilog.logged_call( \
            ['git', '--git-dir=%s' % self.localpath, 'fetch', '--all'], \
            self.logger, \
            self.make_extra('update'))

    def push_branches(self, remotebaseurl, branches):
        contribprefix = 'contrib/'
        destinationpath = repo
        if destinationpath.startswith(contribprefix):
            destinationpath = destinationpath[len(contribprefix):]
        refspec = ['%s:%s' % (branch, branch) for branch in branches]
        minilog.logged_call( \
            ['git', '--git-dir=%s' % self.localpath, 'push', '-f', remotebaseurl + destinationpath] + refspec, \
            self.logger, \
            self.make_extra('push'))

logger = logging.getLogger('sync')
loghandler = logging.FileHandler(logfile)
loghandler.setFormatter(logging.Formatter('%(asctime)s %(repo)-20s %(phase)-6s %(levelname)-8s %(message)s'))
logger.addHandler(loghandler)
logger.setLevel(loglevel)
for repo in repos:
    try:
        syncer = RepoSyncer(repo, logger, loghandler)
        syncer.ensure_exists(sourceurl)
        syncer.update_repo()
        syncer.push_branches(desturl, branches[repo])
    except Exception as e:
        logger.error('syncing failed: %s.' % str(e), extra={'repo' : repo, 'phase' : 'fail'})
