#!/usr/bin/env bash

java -Djavax.xml.validation.SchemaFactory:http://relaxng.org/ns/structure/1.0=org.iso_relax.verifier.jaxp.validation.RELAXNGSchemaFactoryImpl -Dorg.iso_relax.verifier.VerifierFactoryLoader=com.sun.msv.verifier.jarv.FactoryLoaderImpl -jar /devel/odfvalidator/odf/validator/target/odfvalidator-1.1.7-incubating-SNAPSHOT-jar-with-dependencies.jar -e $1
