#!/usr/bin/python3
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#

import json
import os
import subprocess
import time


def get_config(key):
    sock = subprocess.Popen(["git", "config", "-f", ".gitreview", key], stdout=subprocess.PIPE)
    ret = sock.stdout.readline().strip()
    sock.stdout.close()
    return ret.decode("utf-8")

server = get_config("gerrit.host")
port = get_config("gerrit.port")
project = get_config("gerrit.project")
branch = get_config("gerrit.defaultbranch")

sshcommand = ["ssh"]
if port != None and port != "":
    sshcommand.extend(["-p", port])

while True:
    cmd = sshcommand + ["-n", "-o", "ServerAliveInterval=5", server, "gerrit",
            "stream-events", "-s", "comment-added"]
    sock = subprocess.Popen(cmd, stdout=subprocess.PIPE, bufsize=1)

    try:
        for line in iter(sock.stdout.readline, b''):
            event = json.loads(line)

            if event['type'] != "comment-added":
                continue # should never happen
            if 'username' not in event['change']['owner'].keys():
                continue
            if event['change']['owner']['username'] != os.environ['USER']:
                continue
            if event['change']['project'] != project:
                continue
            if event['change']['branch'] != branch:
                continue
            if 'approvals' not in event.keys():
                continue
            if len([approval for approval in event['approvals'] if approval['type'] == "Verified" and approval['value'] == "1"]) != 1:
                continue

            rev = event['patchSet']['revision']
            cmd = sshcommand + [server, "gerrit", "review", "-s", rev]
            print(' '.join(cmd))
            subprocess.call(cmd)
    except KeyboardInterrupt:
        print("Interrupted.")
        break

    print("Socket closed, reconnecting.")
    time.sleep(1)

sock.communicate()

# vim:set shiftwidth=4 softtabstop=4 expandtab:
