#!/bin/bash

# Invoke this script as '/home/$username/git/dev-tools/ciabot/setup/install' or
# so, and it'll handle the update of the code from git to prod.
#
# When cloning new repos, use 'git clone --no-checkout git://gerrit.libreoffice.org/foo.git'
#
# After update, use /sbin/initctl list | grep irkerd (or loircbot), sudo /sbin/start irkerd or sudo /sbin/stop irkerd
# NOTE: it's enough to start/stop irkerd, it'll automatically start/stop loircbot as well, as they are linked.

if [ "$(whoami)" != "ciabot" ]; then
	echo "forgot 'sudo -u ciabot /bin/bash'?"
	exit 1
fi

origin=$(dirname $0)
prefix=/home/ciabot/prod

for i in $origin/../../../irker-cia-proxy/irker-cia-proxy.py \
    $origin/../libreoffice-bugzilla.pl \
    $origin/../libreoffice-bugzilla2.py \
    $origin/../libreoffice-ciabot.pl \
    $origin/../projmap.json \
    $origin/../run-libreoffice-ciabot.pl \
    $origin/../sigui-bugzilla.pl
do
    to=$prefix/$(basename $i)
    if ! diff -q -u $i $to; then
        cat $i > $to
    else
        echo "$to is up to date"
    fi
done

# vim:set shiftwidth=4 softtabstop=4 expandtab:
